import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.scss'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'
import {useEffect, useRef} from 'react'

const Home = () => {
  const parallaxRef = useRef();
  const image1 = useRef();
  const image3 = useRef();
  const image4 = useRef();
  
  useEffect(()=>{
    if(parallaxRef) {
      parallaxRef.current.container.current.addEventListener("scroll", ()=>{
        image1.current.style.transform = `translateY(-${(parallaxRef.current.container.current.scrollTop - 400) / 6}px)`;
        image3.current.style.transform = `translateY(-${(parallaxRef.current.container.current.scrollTop - 400) / 3}px)`;
        image4.current.style.transform = `translateY(-${(parallaxRef.current.container.current.scrollTop - 400) / 6}px)`;
      });
    }
  },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css"></link>
      </Head>
      <main className={styles.main}>
      <Parallax pages={2} className={styles.parallax__container} ref={parallaxRef}>
        <ParallaxLayer offset={0} speed={1.3} factor={1} className={styles.parallax__layer1}>
          <Image className={styles.parallax__layer__img}
            src="/images/parallax-layer1.jpg"
            width={3999}
            height={2837}
            alt='x'/>
        </ParallaxLayer>
        <ParallaxLayer offset={0} speed={1.3} factor={1} className={styles.parallax__layer3}>
          <h2 className={styles.parallax__layer3__logo}>Ready co.</h2>
          <button className={styles.parallax__layer3__button}>Sign in</button>
          <ul className={styles.parallax__layer3__contact}>
            <li className={styles.parallax__layer3__contact__listElement}>
              <Link className={styles.parallax__layer3__contact__listElement__link} target='_blank' href="https://instagram.com/_yunusdogru">
                <span className={styles.desktopLink}>Instagram</span>
                <span className={styles.mobileLink}><i className="uil uil-instagram"></i></span>
              </Link>
            </li>
            <li className={styles.parallax__layer3__contact__listElement}>
              <Link className={styles.parallax__layer3__contact__listElement__link} target='_blank' href="https://linkedin.com/in/yunusdogru">
                <span className={styles.desktopLink}>Linkedin</span>
                <span className={styles.mobileLink}><i className="uil uil-linkedin"></i></span>
              </Link>
            </li>
            <li className={styles.parallax__layer3__contact__listElement}>
              <Link className={styles.parallax__layer3__contact__listElement__link} target='_blank' href="https://github.com/YunusDogru">
                <span className={styles.desktopLink}>Github</span>
                <span className={styles.mobileLink}><i className="uil uil-github"></i></span>
              </Link>
            </li>
            <li className={styles.parallax__layer3__contact__listElement}>
              <Link className={styles.parallax__layer3__contact__listElement__link} target='_blank' href="https://yunusdogru.com.tr">
                <span className={styles.desktopLink}>Portfolio</span>
                <span className={styles.mobileLink}><i className="uil uil-arrow"></i></span>
              </Link>
            </li>
          </ul>
        </ParallaxLayer>
        <ParallaxLayer offset={0} speed={1} factor={1} className={styles.parallax__layer2}>
          <Image className={styles.parallax__layer__img}
            src="/images/parallax-layer2.jpg"
            width={3999}
            height={2837}
            alt='x'/>
            <h1 className={styles.parallax__layer2__title}>Breathtaking.</h1>
        </ParallaxLayer>
        <ParallaxLayer offset={1} speed={1.5} factor={1} className={styles.parallax__layer4}>
          <div className={styles.parallax__layer4__images}>
            <div className={styles.parallax__layer4__images__imgWrap} ref={image1}>
              <Image className={styles.parallax__layer4__images__imgWrap__img1}
                src="/images/east-1.jpg"
                width={640}
                height={960}
                alt='east'/>
                <h1 className={styles.parallax__layer4__images__imgWrap__letter}>E</h1>
            </div>
            <div className={styles.parallax__layer4__images__imgWrap}>
              <Image className={styles.parallax__layer4__images__imgWrap__img2}
                src="/images/east-2.jpg"
                width={640}
                height={960}
                alt='east'/>
                <h1 className={styles.parallax__layer4__images__imgWrap__letter}>A</h1>
            </div>
            <div className={styles.parallax__layer4__images__imgWrap} ref={image3}>
              <Image className={styles.parallax__layer4__images__imgWrap__img3}
                src="/images/east-3.jpg"
                width={640}
                height={960}
                alt='east'/>
                <h1 className={styles.parallax__layer4__images__imgWrap__letter}>S</h1>
            </div>
            <div className={styles.parallax__layer4__images__imgWrap} ref={image4}>
              <Image className={styles.parallax__layer4__images__imgWrap__img4}
                src="/images/east-4.jpg"
                width={640}
                height={960}
                alt='east'/>
                <h1 className={styles.parallax__layer4__images__imgWrap__letter}>T</h1>
            </div>
          </div>
          <div className={styles.parallax__layer4__text}>
            <p> A mountain is a large landform that rises above the surrounding land 
              in a limited area, usually in the form of a peak. A mountiain generally 
              considered to be steeper than a hill. Mountains are formed through tectonic
              forces or volcanism. These forces can locally raise the surface of the earth.
              Mountains erode slowly through the action of rivers, weather conditions and
              glacicers.
            </p>
          </div>
        </ParallaxLayer>
      </Parallax>
      </main>
    </>
  )
}
export default Home;
